### ISSUE TITLE
Is there a way to access the external trigger-in events?

### ISSUE THREAD

**Issue by AndreasAZiegler** [berndpfrommer/event_array_codecs#2]
My goal is to use your [FrequencyCam](https://github.com/berndpfrommer/frequency_cam), but instead of “exporting” the frequency images at a certain frame rate, I want to export them at the time stamps of the trigger-in events (This way I want to synchronize the output with the frames of a frame-based camera). Therefore, I need to get access to these external trigger-in events. Is this possible with this decoder?

**Comment by berndpfrommer** [comment]
Yes, just implement this virtual method:
```
void eventExtTrigger(uint64_t, uint8_t, uint8_t) override {}
```
You can also access the trigger events in python with the
[event_array_py](https://github.com/berndpfrommer/event_array_codecs) repo. It uses the event_array_codecs repository under the hood.

If it helps I can write you a little pybind11 adapter so you can use FrequencyCam from python. Of course if you are a hardcore c++ guy I can save myself the effort :)

**Comment by AndreasAZiegler** [comment]
Thanks a lot for the guidance. I'm definitively not a hardcore c++ guy, but enough comfortable with it (It's the language I used most, hate most and would like to replace with Rust or Julia but didn't have the time yet to do so). Therefore, I appreciate your offer, but in this case you can save yourself the effort.
